### PR TITLE
hash of public params for Nova & HyperNova

### PR DESCRIPTION
**Pull request by arnaucube**
- implement hash of public params for Nova & HyperNova
- abstract pp_hash computation for folding schemes
- add pp_hash to solidity contract generator to verify the decider proof

### CODE REVIEW

**Comment by CPerezz** [comment]
Will review once #116 is merged to focus only on the content of this PR.

Otherwise, can you change the destination of this PR to #116's branch temporarilly to allow for an easier review?

**Review by CPerezz — APPROVED** [review]
LGTM! Nice work!

**Review by CPerezz — COMMENTED** [review]
Ammend

**Review by CPerezz — APPROVED** [review]
LGTM!

**Comment by arnaucube** [comment]
Rebased to latest main branch updates, this PR is now ready to be reviewed.

**Review by dmpierre — APPROVED** [review]

**Pull request merged**
