### PR TITLE
Docs fix spelling issues

### PR DESCRIPTION
**Pull request by nnsW3**
Hello
I found several spelling issues.
Hope it helps
Br, Elias.

### CODE REVIEW

**Comment by arnaucube** [comment]
Hi @nnsW3 , thanks for the typos fixes. In this repo some months ago we added into the CI pipeline the tool [typos](https://github.com/crate-ci/typos) to prevent many typos from happening, but it will only detect miss-spellings of words, not wrong usages or errors on sentences as the ones that you're fixing in this PR.

From what I see in your github profile, eg. https://github.com/Cyfrin/foundry-full-course-cu/pull/2301, https://github.com/starkware-libs/blockifier/pull/2108, https://github.com/near/nearcore/pull/11906, https://github.com/matter-labs/zksync-era/pull/2611 , etc (more than 100 PRs to different projects fixing typos), seems like you're using some more advanced tool to detect these kind of typos that are not misspelling of words but more like sentence errors or wrong usage of words.

Is it some tool that we could integrate in the CI pipeline of this repo, so that future similar typos can be automatically detected avoiding more human friction?
Thanks in advance.

**Comment by CPerezz** [comment]
Can we close this @arnaucube? SO we have less PRs to navigate through

**Comment by nnsW3** [comment]
> Hi @nnsW3 , thanks for the typos fixes. In this repo some months ago we added into the CI pipeline the tool [typos](https://github.com/crate-ci/typos) to prevent many typos from happening, but it will only detect miss-spellings of words, not wrong usages or errors on sentences as the ones that you're fixing in this PR.
> 
> From what I see in your github profile, eg. [Cyfrin/foundry-full-course-cu#2301](https://github.com/Cyfrin/foundry-full-course-cu/pull/2301), [starkware-libs/blockifier#2108](https://github.com/starkware-libs/blockifier/pull/2108), [near/nearcore#11906](https://github.com/near/nearcore/pull/11906), [matter-labs/zksync-era#2611](https://github.com/matter-labs/zksync-era/pull/2611) , etc (more than 100 PRs to different projects fixing typos), seems like you're using some more advanced tool to detect these kind of typos that are not misspelling of words but more like sentence errors or wrong usage of words.
> 
> Is it some tool that we could integrate in the CI pipeline of this repo, so that future similar typos can be automatically detected avoiding more human friction? Thanks in advance.

no, I done it manually

**Comment by arnaucube** [comment]
But, are you reading line by line all those repositories where you open PRs fixing issues in order to find those kind of typos? We're talking about more than 100 PRs to 100 different repos, each of them with thousands lines of code. I would use some tool instead.

I was asking because maybe we can integrate that tool in the CI so that in the future similar typos are detected automatically.

**Pull request merged**
