### PR TITLE
Implement Frontend Interface

### PR DESCRIPTION
**Pull request by yugocabrio**
### Implement Frontend Interface and Its Traits for R1CS and CCS Extraction

This pull request introduces the `Frontend` interface as outlined in Issue #15. The interface defines how circuits are connected to folding-schemes, specifically facilitating the extraction of R1CS and CCS structures. Implementations for this interface have been provided for both the Arkworks and Circom frameworks.

**Main Changes:**

- Introduced the `Frontend` trait with methods `extract_r1cs_and_z` and `extract_ccs_and_z` as per the circuit tool.
- Implemented the `Frontend` trait for the `ConstraintSystem` from `Arkworks` and the `CircomWrapper` from `Circom`.
- Provided tests under the `frontend_tests` module to validate the trait's functionality across both frameworks.

**Usage**
Arkworks
```
let cs = ConstraintSystem::<Fr>::new_ref();
let frontend: &dyn Frontend<Projective, Fr> = &cs;
let (r1cs, z_r1cs) = frontend.extract_r1cs_and_z(&[].as_slice()).unwrap();
let (ccs, z_ccs) = frontend.extract_ccs_and_z(&[].as_slice()).unwrap();
```
Circom
```
let frontend = CircomWrapper::<Bn254>::new(r1cs_filepath, wasm_filepath);
let (r1cs, z_r1cs) = frontend.extract_r1cs_and_z(&[("input_name", vec![BigInt::from(3)])]).unwrap();
let (ccs, z_ccs) = frontend.extract_ccs_and_z(&[("input_name", vec![BigInt::from(3)])]).unwrap();
```

**Feedback**
I kindly request reviewers to verify that the code meets the requirements. Thanks in advance!

### CODE REVIEW

**Comment by arnaucube** [comment]
I'm afraid that we don't have yet enough info to define a frontend trait interface.
For example, now that we have [Nova's AugmentedFCircuit implemented](https://github.com/privacy-scaling-explorations/folding-schemes/pull/33), it is a bit clearer how the frontend trait interface might look, eg. having a method to generate the constraints of the current step and returning the witness vector (eg. `generate_step_constraints`) to be used as part of the constraints of the AugmentedFCircuit.

Before doing the part of the AugmentedFCircuit in the code, we didn't had awareness of these needs. This can be covered with the current existing methods of `extract_{r1cs/z}`, but the trait will not be directly the methods that exist in frontend/arkworks & frontend/circom just exposed as a trait as it is in this PR.

I appreciate your effort, and sorry for the radio silence, but for the moment I would suggest to come back at the `frontend trait` in some time, once other pieces are more advanced and we have the whole picture to evaluate how the trait should look. If you're still interested into this, once we have the other parts more stable I can ping you in the issue #15 with a more complete definition of the trait so you can work on it.

**Comment by arnaucube** [comment]
Hi @yugocabrio , we're now in a stage in which we have more clear view on how the whole frontend interface would look like.
The `extract_r1cs`, `extract_z`, `extract_w_x`, `extract_r1cs_and_z` methods were actually not needed in the frontend interface, but just internally in the folding scheme code (and only two of them), and the `frontend/arkworks` implementation was not even needed.

The only needed thing for the frontend is to fulfill the interface of the `FCircuit`. So a task needed now is to update the `frontend/circom` (code that you already did in https://github.com/privacy-scaling-explorations/folding-schemes/pull/26 ) and adapt it to fit into the `FCircuit` trait. This is the issue to track it: https://github.com/privacy-scaling-explorations/folding-schemes/issues/55

Would you like to do it? If so, I can ping you once the latest changes (https://github.com/privacy-scaling-explorations/folding-schemes/pull/54) are merged, so then you can work on it.

**Comment by arnaucube** [comment]
Hi, @yugocabrio , is it fine if we close this PR (#32) since you're working on this in https://github.com/privacy-scaling-explorations/folding-schemes/pull/71 ?

**Comment by yugocabrio** [comment]
Yes, it's fine.

**Comment by arnaucube** [comment]
Closing this PR since it's being done at the other PR: https://github.com/privacy-scaling-explorations/sonobe/pull/71

**Pull request closed without merging**
